<html>
<head>
  <meta charset="utf-8" />
  <base href="/" />
  <title>Тестовый сайт</title>
  <link href="css/bootstrap.css" rel="stylesheet">
  <link href="css/bootstrap-theme.css" rel="stylesheet">
  <link href="css/signin.css" rel="stylesheet">
</head>
<body>

<?php
  if(isset($_SESSION['login'])){
    require 'views/user/menu.phtml';
  }
?>
<?php
  // блок для вывода флешек. можно разделить на зеленые и красные - $_SESSION['flash']['error'] и $_SESSION['flash']['success']
  if(isset($_SESSION['flash'])) {
    echo "<div class='alert alert-info'>".$_SESSION['flash']."</div>";
    unset($_SESSION['flash']);
  }
?>
    <div class="container">
