<!-- редактирование данных пользователя-->
<form action='' method="POST">
  <input type="text" name="firstname" value="<?php echo $usr['firstname']; ?>"/>
  <input type="text" name="lastname" value="<?php echo $usr['lastname']; ?>"/>
  <!-- и тд-->
  <input type="submit" name="edit_user" class='btn btn-default'/>
  <a href='/admin/'>
  <button type='button' class='btn btn-default '>Список пользователей</button>
  </a>
</form>
